wallet:
  public_key: ''
pool:
  threads: 2
  server: 127.0.0.1
  port: 10001
blockchain:
  threads: 2
  server: 127.0.0.1
  port: 10002
metronome:
  threads: 2
  server: 127.0.0.1
  port: 10003
validator:
  proof_pos:
    threads_hash: 2
    threads_io: 1
    bucket_size: 32768
    buckets: 256
    disk: 10G
    enable: false
    vault: ~/dsc-pos.vault
  fingerprint: ''
  port: 10004
  proof_pom:
    memory: 1G
    threads_hash: 2
    enable: false
  public_key: ''
  proof_pow:
    threads_hash: 2
    enable: true
  server: 127.0.0.1
